// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "ball_t.h"

static int __ball_t_hash_computed;
static int64_t __ball_t_hash;

int64_t __ball_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ball_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__ball_t_get_hash;
    (void) cp;

    int64_t hash = (int64_t)0x28f1bc4c1af0a391LL
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __int64_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __ball_t_get_hash(void)
{
    if (!__ball_t_hash_computed) {
        __ball_t_hash = __ball_t_hash_recursive(NULL);
        __ball_t_hash_computed = 1;
    }

    return __ball_t_hash;
}

int __ball_t_encode_array(void *buf, int offset, int maxlen, const ball_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].color), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].velocity, 2);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int ball_t_encode(void *buf, int offset, int maxlen, const ball_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ball_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __ball_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __ball_t_encoded_array_size(const ball_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int8_t_encoded_array_size(&(p[element].id), 1);

        size += __int8_t_encoded_array_size(&(p[element].color), 1);

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __double_encoded_array_size(p[element].position, 2);

        size += __double_encoded_array_size(p[element].velocity, 2);

    }
    return size;
}

int ball_t_encoded_size(const ball_t *p)
{
    return 8 + __ball_t_encoded_array_size(p, 1);
}

size_t ball_t_struct_size(void)
{
    return sizeof(ball_t);
}

int ball_t_num_fields(void)
{
    return 5;
}

int ball_t_get_field(const ball_t *p, int i, lcm_field_t *f)
{
    if (0 > i || i >= ball_t_num_fields())
        return 1;
    
    switch (i) {
    
        case 0: {
            f->name = "id";
            f->type = LCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void *) &p->id;
            return 0;
        }
        
        case 1: {
            f->name = "color";
            f->type = LCM_FIELD_INT8_T;
            f->typestr = "int8_t";
            f->num_dim = 0;
            f->data = (void *) &p->color;
            return 0;
        }
        
        case 2: {
            f->name = "utime";
            f->type = LCM_FIELD_INT64_T;
            f->typestr = "int64_t";
            f->num_dim = 0;
            f->data = (void *) &p->utime;
            return 0;
        }
        
        case 3: {
            f->name = "position";
            f->type = LCM_FIELD_DOUBLE;
            f->typestr = "double";
            f->num_dim = 1;
            f->dim_size[0] = 2;
            f->dim_is_variable[0] = 0;
            f->data = (void *) &p->position;
            return 0;
        }
        
        case 4: {
            f->name = "velocity";
            f->type = LCM_FIELD_DOUBLE;
            f->typestr = "double";
            f->num_dim = 1;
            f->dim_size[0] = 2;
            f->dim_is_variable[0] = 0;
            f->data = (void *) &p->velocity;
            return 0;
        }
        
        default:
            return 1;
    }
}

const lcm_type_info_t *ball_t_get_type_info(void)
{
    static int init = 0;
    static lcm_type_info_t typeinfo;
    if (!init) {
        typeinfo.encode         = (lcm_encode_t) ball_t_encode;
        typeinfo.decode         = (lcm_decode_t) ball_t_decode;
        typeinfo.decode_cleanup = (lcm_decode_cleanup_t) ball_t_decode_cleanup;
        typeinfo.encoded_size   = (lcm_encoded_size_t) ball_t_encoded_size;
        typeinfo.struct_size    = (lcm_struct_size_t)  ball_t_struct_size;
        typeinfo.num_fields     = (lcm_num_fields_t) ball_t_num_fields;
        typeinfo.get_field      = (lcm_get_field_t) ball_t_get_field;
        typeinfo.get_hash       = (lcm_get_hash_t) __ball_t_get_hash;
    }
    
    return &typeinfo;
}
int __ball_t_decode_array(const void *buf, int offset, int maxlen, ball_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].color), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].velocity, 2);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __ball_t_decode_array_cleanup(ball_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_decode_array_cleanup(&(p[element].id), 1);

        __int8_t_decode_array_cleanup(&(p[element].color), 1);

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __double_decode_array_cleanup(p[element].position, 2);

        __double_decode_array_cleanup(p[element].velocity, 2);

    }
    return 0;
}

int ball_t_decode(const void *buf, int offset, int maxlen, ball_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ball_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __ball_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ball_t_decode_cleanup(ball_t *p)
{
    return __ball_t_decode_array_cleanup(p, 1);
}

int __ball_t_clone_array(const ball_t *p, ball_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_clone_array(&(p[element].id), &(q[element].id), 1);

        __int8_t_clone_array(&(p[element].color), &(q[element].color), 1);

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __double_clone_array(p[element].position, q[element].position, 2);

        __double_clone_array(p[element].velocity, q[element].velocity, 2);

    }
    return 0;
}

ball_t *ball_t_copy(const ball_t *p)
{
    ball_t *q = (ball_t*) malloc(sizeof(ball_t));
    __ball_t_clone_array(p, q, 1);
    return q;
}

void ball_t_destroy(ball_t *p)
{
    __ball_t_decode_array_cleanup(p, 1);
    free(p);
}

int ball_t_publish(lcm_t *lc, const char *channel, const ball_t *p)
{
      int max_data_size = ball_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ball_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _ball_t_subscription_t {
    ball_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void ball_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    ball_t p;
    memset(&p, 0, sizeof(ball_t));
    status = ball_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ball_t!!!\n", status);
        return;
    }

    ball_t_subscription_t *h = (ball_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ball_t_decode_cleanup (&p);
}

ball_t_subscription_t* ball_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    ball_t_handler_t f, void *userdata)
{
    ball_t_subscription_t *n = (ball_t_subscription_t*)
                       malloc(sizeof(ball_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 ball_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg ball_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ball_t_subscription_set_queue_capacity (ball_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int ball_t_unsubscribe(lcm_t *lcm, ball_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe ball_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

