"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ball_t(object):
    __slots__ = ["id", "color", "utime", "position", "velocity"]

    def __init__(self):
        self.id = 0
        self.color = 0
        self.utime = 0
        self.position = [ 0.0 for dim0 in range(2) ]
        self.velocity = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(ball_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bbq", self.id, self.color, self.utime))
        buf.write(struct.pack('>2d', *self.position[:2]))
        buf.write(struct.pack('>2d', *self.velocity[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ball_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ball_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ball_t()
        self.id, self.color, self.utime = struct.unpack(">bbq", buf.read(10))
        self.position = struct.unpack('>2d', buf.read(16))
        self.velocity = struct.unpack('>2d', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ball_t in parents: return 0
        tmphash = (0x28f1bc4c1af0a391) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ball_t._packed_fingerprint is None:
            ball_t._packed_fingerprint = struct.pack(">Q", ball_t._get_hash_recursive([]))
        return ball_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

