# Camera parameters

# D435 Serial Numbers
# Light Blue: 819112070800
# Green: 817512071338
# Purple: 819112072448
# Orange: 819112070694
#
# T265 Serial Numbers
# 845412110102

forward:
  enabled: false
  width: 640
  height: 480
  fps: 15                # 15, 30, or 60
  serial: "819112070800" # 12 digit number on bottom of realsense camera
  publish_rgbd: true
  publish_pointcloud: true
  enable_autoexposure: false
  publish_pose: false # tracking camera only
  rotation: # 3x3 rotation matrix left to right first, then top to bottom
    - 1
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 1
  translation: # 3x1 translation vector
    - 0
    - 0
    - 0
  sim_rotation: [
    0, 0, 1,
    -1, 0, 0,
    0, -1, 0
  ]
  sim_translation: [0, 0, 0]

downward:
  enabled: false
  width: 640
  height: 480
  fps: 30                # 15, 30, or 60
  serial: "819112070694" # 12 digit number on bottom of realsense camera
  publish_rgbd: false
  publish_pointcloud: true
  enable_autoexposure: false
  publish_pose: false # tracking camera only
  rotation: # 3x3 rotation matrix left to right first, then top to bottom
    - 1
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 1
  translation: # 3x1 translation vector
    - 0
    - 0
    - 0

other-forward: # To accomodate the t265 in use with the other cameras
  enabled: false
  width: 640
  height: 480
  fps: 30                # 15, 30, or 60
  #serial: "909212110206" 
  serial: "845412110102" # 12 digit number on bottom of realsense camera
  publish_rgbd: false
  publish_pointcloud: false
  enable_autoexposure: true
  publish_pose: true # tracking camera only
  rotation: # 3x3 rotation matrix left to right first, then top to bottom
    - 1
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 1
  translation: # 3x1 translation vector
    - 0
    - 0
    - 0
